### ISSUE TITLE
Basic Component | Modal

### ISSUE THREAD

**Issue by maulanasdqn** [psudevteam/psuservice#16]
- [ ] Reusable Modal
- [x] Has Title Porps
- [x] Has Content Props
- [ ] Has With Close Props
- [ ] Has Button Props ( Submit and Cancel )
- [x] Has onSubmit Props
- [x] Has onCancel Props

**Comment by EL5225** [comment]
modal nya digunain buat apa sir?

**Comment by maulanasdqn** [comment]
> modal nya digunain buat apa sir?

buat update, delete dan add
